name: jejom
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  dynamic_color: ^1.7.0
  firebase_core: ^3.3.0
  flutter:
    sdk: flutter
  flutter_swipe_button: ^2.1.1+1
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  o3d: ^3.1.2
  provider: ^6.1.2
  swipeable_button_view: ^0.0.2
  widget_circular_animator: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/