name: jejom
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  cloud_firestore: ^5.2.1
  dynamic_color: ^1.7.0
  firebase_core: ^3.3.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_staggered_animations: ^1.1.1
  flutter_swipe_button: ^2.1.1+1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  image_picker: ^0.8.4+4
  google_maps_flutter: 2.6.1
  location: ^5.0.0
  lottie: ^3.1.2
  m3_carousel: ^1.0.2
  o3d: ^3.1.2
  provider: ^6.1.2
  swipeable_button_view: ^0.0.2
  widget_circular_animator: ^1.0.0
  crystal_navigation_bar: ^1.0.0
  star_menu: ^4.0.1
  url_launcher: ^6.3.0
  uuid: ^4.4.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/images/
    - assets/balloon_fireworks.json