name: jejom
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  cloud_firestore: ^5.2.1
  dynamic_color: ^1.7.0
  firebase_core: ^3.3.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_staggered_animations: ^1.1.1
  flutter_swipe_button: ^2.1.1+1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  image_picker: ^0.8.4+4
  google_maps_flutter: 2.6.1
  location: ^5.0.0
  lottie: ^3.1.2
  m3_carousel: ^1.0.2
  o3d: ^3.1.2
  provider: ^6.1.2
  swipeable_button_view: ^0.0.2
  widget_circular_animator: ^1.0.0
  crystal_navigation_bar: ^1.0.0
  star_menu: ^4.0.1
  url_launcher: ^6.3.0
  uuid: ^4.4.2
  shared_preferences: ^2.2.3
  http: ^1.2.2
  flutter_launcher_icons: ^0.13.1
  geocoding: ^3.0.0
  firebase_storage: ^12.2.0
  geolocator: ^12.0.0
  numberpicker: ^2.1.2
  flutter_rating: ^2.0.2
  easy_date_timeline: ^1.1.3
  sticky_headers: ^0.3.0+2
  story_view: ^0.16.5
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/jejomLogo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/jejomLogo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/jejomLogo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/jejomLogo.png"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/images/
    - assets/balloon_fireworks.json
  
  # Add font configuration for Akzidenz-Grotesk
  fonts:
    - family: Akzidenz-Grotesk
      fonts:
        - asset: assets/akzidenz-grotesk/Akzidenz-grotesk-roman.ttf
          weight: 400
        - asset: assets/akzidenz-grotesk/Akzidenz-grotesk-bold.ttf
          weight: 700
        - asset: assets/akzidenz-grotesk/Akzidenz-grotesk-black.ttf
          weight: 900
        - asset: assets/akzidenz-grotesk/Akzidenz-grotesk-light.ttf
          weight: 300
        - asset: assets/akzidenz-grotesk/verthold-akzidenz-grotesk-be-italic.ttf
          style: italic